--DROP TABLE EQUIPOS;
--DROP EQUIPOS;

CREATE TABLE EQUIPOS
(
Codigo NUMBER(5),
Nombre VARCHAR2(35),
Direccion CHAR(80),
PRIMARY KEY(Codigo)
)

CREATE TABLE JUGADORES
(
Id NUMBER(5),
Nombre VARCHAR2(35),
Apellido VARCHAR2(35),
Estatura NUMBER(3,2),
FechaN DATE,
CodigoE NUMBER(5) REFERENCES EQUIPOS,
PRIMARY KEY (Id)
--FOREIGN KEY (CodigoE) REFERENCES EQUIPOS(Codigo)
)



